[package]
name = "ch11-02-running-tests"
version = "0.1.0"
authors = ["Laurent Couvidou <hello@lorancou.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
