[package]
name = "ch14-01-release-profiles"
version = "0.1.0"
authors = ["Laurent Couvidou <hello@lorancou.net>"]
edition = "2021"

[profile.dev]
opt-level = 1               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.

[dependencies]
