[package]
name = "ch08-ex2-pig-latin"
version = "0.1.0"
authors = ["Laurent Couvidou <lorancou@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
